services:
  app:
    build: .
    container_name: tripatrasvc
    restart: always
    ports:
      - "${APP_PORT}:3000"
    volumes:
      - .:/app
    depends_on:
      - db
    env_file:
      - .env
    command: ["air", "-c", ".air.toml"]

  db:
    image: mongo:latest
    container_name: tripatrasvc_db
    restart: always
    ports:
      - "${MONGO_PORT}:27017"
    env_file:
      - .env
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_DB}
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data:
